### ISSUE TITLE
배포환경 구성

### ISSUE THREAD

**Issue by hyesungoh** [dogVelopers/whereWeGoWebClient#23]
### Description

배포 수단을 정한 후 개발 및 자동화 환경 개발

### Task

- [x] 배포 수단 정하기
- [x] CICD 수단 정하기
- [x] 배포
- [x] CICD 개발 및 적용
